version: '3'

networks:
  frontend:
    external:
      name: frontend

  monitor:
    external:
      name: monitor

services:
  nginx:
    image: "nginx:latest"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "8081:8081"
    restart: always
    networks:
      - frontend
      - monitor