version: '3'

networks:
  frontend:
    external:
      name: frontend

  monitor:
    external:
      name: monitor

services:
  nginx:
    image: "nginx:latest"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "8081:8081"
      - "8082:8082"
      - "9901:9901"
      - "9902:9902"
      - "9903:9903"
    restart: always
    networks:
      - frontend
      - monitor

  apache:
    image: "httpd:latest"
    volumes:
      - ./httpd/htdocs:/usr/local/apache2/htdocs/:ro
    restart: always
    expose:
      - "80"
    networks:
      - frontend