version: '3'

services:
  gnuradio:
    build: ./gnuradio

  tlesync:
    build: ./tlesync
    volumes:
      - ./persistent-data/TLE:/app/TLE

  receiver:
    build: ./receiver
    environment:
      - SAMP=30000
      - DISPLAY=10.0.0.51:0.0
    volumes:
      - ./persistent-data/TLE:/app/TLE
      - ./persistent-data/input:/app/input

  decoder:
    build: ./decoder
    environment:
      - DISPLAY=10.0.0.51:0.0
    volumes:
      - ./persistent-data/input:/app/input
      - ./persistent-data/output:/app/output
