version: '3'

networks:
  frontend:

volumes:
  portainer_data:


services:

  gnuradio:
    build: ./gnuradio

  tlesync:
    build: ./tlesync
    volumes:
      - ./persistent-data/TLE:/app/TLE

  receiver:
    build: ./receiver
    volumes:
      - ./persistent-data/TLE:/app/TLE
      - ./persistent-data/input:/app/input

  decoder:
    build: ./decoder
    volumes:
      - ./persistent-data/input:/app/input
      - ./persistent-data/output:/app/output


  nginx:
    build: ./nginx
    depends_on:
      - apache
      - portainer
    ports:
      - "80:80"
      - "8081:8081"
    restart: always
    networks:
      - frontend

  apache:
    build: ./httpd
    volumes:
      - ./persistent-data/TLE:/app/TLE
      - ./persistent-data/input:/app/input
      - ./persistent-data/output:/app/output
    restart: always
    networks:
      - frontend

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - frontend
