scrape_configs:
- job_name: prometheus
  scrape_interval: 10s
  scrape_timeout: 10s
  static_configs:
  - targets: 
    - localhost:9090
- job_name: node
  scrape_interval: 10s
  scrape_timeout: 10s
  static_configs:
  - targets: 
    - prometheus_node:9100
- job_name: cadvisor
  scrape_interval: 10s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - cadvisor:8080