version: '3'

services:
  gnuradio:
    build: 
      context: .
      dockerfile: ./gnuradio/Dockerfile

  tlesync:
    build: 
      context: .
      dockerfile: ./tlesync/Dockerfile
    volumes:
      - ../persistent-data/config:/app/config:rw

  scheduler:
    build: 
      context: .
      dockerfile: ./scheduler/Dockerfile
    volumes:
      - ../persistent-data/config:/app/config:ro

  importer:
    build: 
      context: .
      dockerfile: ./importer/Dockerfile
    depends_on:
      - gnuradio
    volumes:
      - ../persistent-data/config:/app/config:ro
      - ../persistent-data/import:/app/import:ro
      - ../persistent-data/input:/app/input:rw

  receiver:
    build: 
      context: .
      dockerfile: ./receiver/Dockerfile
    depends_on:
      - gnuradio
    ports:
      - "7373:7373"
    volumes:
      - ../persistent-data/config:/app/config:ro
      - ../persistent-data/input:/app/input:rw
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb

  decoder:
    build: 
      context: .
      dockerfile: ./decoder/Dockerfile
    depends_on:
      - gnuradio
    volumes:
      - ../persistent-data/config:/app/config:ro
      - ../persistent-data/input:/app/input:ro
      - ../persistent-data/output:/app/output:rw