version: '3'

volumes:
  portainer_data:
  grafana_data:

networks:
  monitor:
    external:
      name: monitor

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - portainer_data:/data:rw
    restart: always
    expose:
      - "9000"
    networks:
      - monitor

  grafana:
    image: raymondmm/grafana:latest
    volumes:
      - ./grafana/config.ini:/etc/grafana/config.ini:rw
      - ./grafana/dashboards:/var/lib/grafana/dashboards:rw
      - ./grafana/provisioning:/etc/grafana/provisioning:rw
    depends_on:
      - prometheus
    restart: always
    expose:
      - "3000"
    networks:
      - monitor

  prometheus:
    image: napnap75/rpi-prometheus:prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - prometheus_node
      - cadvisor
    restart: always
    expose:
      - "9090"
    networks:
      - monitor

  prometheus_node:
    image: napnap75/rpi-prometheus:node_exporter
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: always
    expose:
      - "9100"
    networks:
      - monitor

  cadvisor:
    image: budry/cadvisor-arm:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: always
    expose:
      - "8080"
    networks:
      - monitor